### ISSUE TITLE
Unable to run most algos

### ISSUE THREAD

**Issue by joshwigginton** [fbertram/TuringTrader#14]
Hello, I was trying to use the new preview version of Turning and ran into some issues trying to run the v2 Algos. 

1. Showcase Algo v2 - Seems like only the 60/40 will run under showcase algov2. Here is an example of error from BAA-G4, same or similar error to all others in that folder.

running algorithm Keller's Bold Asset Allocation (BAA-G4)
EXCEPTION: One or more errors occurred. (AlgorithmLoader: algorithm Benchmark_60_40 is ambiguous)   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at TuringTrader.SimulatorV2.TimeSeriesAsset.get_Meta() in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\TimeSeries.cs:line 388
   at TuringTrader.SimulatorV2.TimeSeriesAsset.get_Description() in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\TimeSeries.cs:line 393
   at TuringTrader.BooksAndPubsV2.Keller_BAA_Core.<Run>b__39_0()
   at TuringTrader.SimulatorV2.Algorithm.<>c__DisplayClass71_0.<SimLoop>b__0() in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\Algorithm.cs:line 255
   at TuringTrader.SimulatorV2.Algorithm.<>c__DisplayClass70_0.<_simLoopOuter>b__0(Double prev) in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\Algorithm.cs:line 226
   at TuringTrader.SimulatorV2.Algorithm._simLoop(Func`2 innerBarFun, Double init) in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\Algorithm.cs:line 212
   at TuringTrader.SimulatorV2.Algorithm._simLoopOuter(Func`1 innerBarFun) in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\Algorithm.cs:line 226
   at TuringTrader.SimulatorV2.Algorithm.SimLoop(Action barFun) in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader.Simulator\Simulator\v2\Core\Algorithm.cs:line 253
   at TuringTrader.BooksAndPubsV2.Keller_BAA_Core.Run()
   at TuringTrader.MainWindow.<>c__DisplayClass35_0.<RunButton_Click>g__uiThread|1() in C:\Users\fbert\OneDrive\Documents\TuringTrader\TuringTrader\MainWindow.xaml.cs:line 554
finished algorithm Keller's Bold Asset Allocation (BAA-G4) after 2.5 seconds

2. Showcase Algo v2 - running Stocks on the Move, just freeze and you have to exit the program and open up again. 
3. Showcase Algo (not v2) - not sure if these are supposed to be backwards compatible, but get the following error when I attempt to run them: 

failed to instantiate TuringTrader.Simulator.AlgorithmInfo

4. Most of the V2 Demo Algos work, but "Portfolios" and Stocks gives this error 
Line 128: CS0103 - The name 'AlgorithmConstants' does not exist in the current context
Line 129: CS0103 - The name 'AlgorithmConstants' does not exist in the current context
Line 134: CS0103 - The name 'AlgorithmConstants' does not exist in the current context

5. WalkforwardOptimizations gives the following error

Line 39: CS0246 - The type or namespace name 'OptimizerParamAttribute' could not be found (are you missing a using directive or an assembly reference?)
Line 39: CS0246 - The type or namespace name 'OptimizerParam' could not be found (are you missing a using directive or an assembly reference?)
Line 58: CS0246 - The type or namespace name 'OptimizerGrid' could not be found (are you missing a using directive or an assembly reference?)

**Comment by joshwigginton** [comment]
Solved by deleting the items in the home directory from old install.

**Comment by fbertram** [comment]
I am planning to have a better upgrade mechanism before the full release of "16." In the meantime, I added some additional notes on the download page.
